--insert into pizza (name, pizza_size, cafe_id, ingredients, price) values('Margarita', 'XL', 1, 'Tomaten, Mozarello, Sauce', 10.00);
--insert into pizza (name, pizza_size, cafe_id, ingredients, price) values('ChickenPizza', 'XXL', 1, 'Chicken, SandwichSauce, Cheese', 11.00);
--insert into pizza (name, pizza_size, cafe_id, ingredients, price) values('Salami', 'XXL', 2, 'Tomaten, Salami, Cheese', 11.00);
--insert into pizza (name, pizza_size, cafe_id, ingredients, price) values('Pizza Hawaii', 'XL', 2, 'Tomaten, Schinken, Cheese, Ananas', 11.00);
--insert into pizza (name, pizza_size, cafe_id, ingredients, price) values('Mediterranea', 'XXL', 3, 'Tomaten, Spinat, Weichkäse, Knoblauch', 11.00);
--insert into pizza (name, pizza_size, cafe_id, ingredients, price) values('Pizza Rustica', 'XXL', 3, 'Tomaten, Champignons, Cheese, Salami', 11.00);
--
--
--insert into cafe (name, city, address, email, phone, open_at, close_at) values('Paradise', 'Berlin', 'Franfurter Allee 21', 'paradiser@gmail.com', '176 45832122', '09:00', '22:00');
--insert into cafe (name, city, address, email, phone, open_at, close_at) values('Paradise2', 'Köln', 'Steinmühle 1', 'paradiser2@gmail.com', '176 458354325', '09:00', '23:00');
--insert into cafe (name, city, address, email, phone, open_at, close_at) values('Paradise3', 'Stuttgart', 'Giflitzer 12', 'paradiser3@gmail.com', '176 45867698', '10:00', '23:00');
